name: Increment Minor Version

on:
  pull_request:
    types:
      - closed

jobs:
  increment-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    steps:
      - name: Checkout, Set up Git, Extract version, Check version change, Increment, Commit, and Push
        run: |
          # Checkout repository
          git checkout ${{ github.sha }}
          
          # Set up Git
          git config --global user.name "github-bot"
          git config --global user.email "github-bot@user-github-bot.com"
          
          # Extract current version
          current_version=$(grep 'libVersion=' gradle.properties | cut -d'=' -f2)
          
          # Check if libVersion was changed
          git fetch origin main
          if git diff origin/main...HEAD -- gradle.properties | grep 'libVersion='; then
            version_changed=true
          else
            version_changed=false
          fi
          
          # Increment minor version if not changed
          if [ "$version_changed" = false ]; then
            IFS='.' read -r major minor patch <<< "$current_version"
            minor=$((minor + 1))
            new_version="$major.$minor.0"
          
            # Update gradle.properties with new version
            sed -i "s/libVersion=$current_version/libVersion=$new_version/" gradle.properties
          
            # Commit and push new version
            git add gradle.properties
            git commit -m "Increment version to $new_version"
            git push origin HEAD:main
          fi

